### ISSUE TITLE
Not sending/forwarding message if conversation is not active

### ISSUE THREAD

**Issue by ticoti** [Josepdal/DBTeamV2#19]
Not sending/forwarding message if conversation is not active, when you talk and then inmediately send/fwd to that conversation, it does work

**Comment by otgo** [comment]
Please describe yet most your bug, we can't understand you, sorry.

**Comment by ticoti** [comment]
function send_msg and forward_msg does not work when you are using it to send the msg to a conversation which is not intervening in the command.

Example:

sending the report of spam of a group to the admin, is not working unless the admin talks to the bot moments before the report is sent

**Comment by otgo** [comment]
Which command?
Where?
Plugin? Backtrace?.

**Comment by Josepdal** [comment]
We already know about that issues. We are trying to solve them... We will reference this issue as soon as we get the solution. Thanks for your report! 😘

**Comment by iicc1** [comment]
This must be solved now, tg-cli "forgets" data when is rebooted and does not get the chats when the conversation is not "reactived". But now, cli loads all data at start and should found all the chat id's.
