### ISSUE TITLE
attempt to index local 'msgb'

### ISSUE THREAD

**Issue by ghost** [Josepdal/DBTeamV2#3]
Hi 
I have problem with this source :
[Ready] 0>  *** 1484571986.000000 lua: ./bot/bot.lua:150: attempt to index local 'msgb' (a nil value)

**Comment by Josepdal** [comment]
Will be fixed soon, it happens sometimes when some folder is missing.

**Comment by ghost** [comment]
Ok thanks .

**Comment by Josepdal** [comment]
Fixed!
