### ISSUE TITLE
fail to run ./launch.sh

### ISSUE THREAD

**Issue by ranrinc** [Josepdal/DBTeamV2#38]
It seems that ./launch.sh doesnt run anything with many error saying that lua52 files is not found. Unsure how to make it run. Help will be appreciated

**Comment by iicc1** [comment]
Have you do `./launch.sh install` before?
Could you send the errors?
In which operating system are you installing it?

**Comment by ranrinc** [comment]
Hi there,

thanks for the reply, yes I do run step-by-step on my cloud server. I tested on Ubuntu and Debian without luck. Each server execute as your instruction. Currently I destroy all the server, so I wont be able to give you the error message. However upon running ./launch.sh after ./launch.sh install it show that not find file lua52. I did forget about the full directory but its under /usr

I hope to have this resolve and planning to try again tommorow

**Comment by ranrinc** [comment]
As promises, I setup a new machine running Ubuntu 16.04 fresh install
running step:

sudo apt-get update
sudo apt-get install git redis-server libconfig8-dev libjansson-dev lua5.2 liblua5.2-dev lua-lgi glib-2.0 libnotify-dev libssl-dev libssl1.0.0 make libstdc++6 g++-4.9 unzip tmux -y

git clone https://github.com/Josepdal/DBTeamV2.git
 cd DBTeamV2
 chmod +x launch.sh
 ./launch.sh install # you can use the option --no-download and only configure DBTeam
 ./launch.sh # Will ask you for a phone number & confirmation code.

The error that I receive after the last command

root@RichardCloudDevelopment:~/DBTeamV2# ./launch.sh

	 ____  ____ _____
	|    \|  _ )_   _|___ ____   __  __
	| |_  )  _ \ | |/ .__|  _ \_|  \/  |
	|____/|____/ |_|\____/\_____|_/\/\_|  v2


change_user_group: can't find the user telegramd to switch to
Telegram-cli version 1.5.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses tdlib (commit f2e430a3d4e4fa61ea040950072dc65b79efa26f)
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libreadline
I: config dir=[/root/.telegram-cli]
I: config file=[/root/.telegram-cli/config]
[/root/.telegram-cli] created
I: profile = '(null)'
I: config_directory = '/root/.telegram-cli/'
I: data_directory = '/root/.telegram-cli//data'
I: logname = '(null)'
[/root/.telegram-cli//data] created
 *** 1496036435.000000 lua: ./bot/bot.lua:12: module 'redis' not found:
	no field package.preload['redis']
	no file '/usr/local/share/lua/5.2/redis.lua'
	no file '/usr/local/share/lua/5.2/redis/init.lua'
	no file '/usr/local/lib/lua/5.2/redis.lua'
	no file '/usr/local/lib/lua/5.2/redis/init.lua'
	no file '/usr/share/lua/5.2/redis.lua'
	no file '/usr/share/lua/5.2/redis/init.lua'
	no file './redis.lua'
	no file '.luarocks/share/lua/5.2/redis.lua'
	no file './bot/redis.lua'
	no file '/usr/local/lib/lua/5.2/redis.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/redis.so'
	no file '/usr/lib/lua/5.2/redis.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './redis.so'
	no file '.luarocks/lib/lua/5.2/redis.so'

Need your assistant, please let me know

**Comment by iicc1** [comment]
Redis is missing: `luarocks install redis-lua`

**Comment by ranrinc** [comment]
@iicc1 I try everything for installing luarocks add gcc to complile luarocks install redis-lua and still having the same error message. Changing the server to from ubuntu to debian with the same result
any idea?

root@richardclouddevelopment:~/DBTeamV2# ./launch.sh install
	 ____  ____ _____
	|    \|  _ )_   _|___ ____   __  __
	| |_  )  _ \ | |/ .__|  _ \_|  \/  |
	|____/|____/ |_|\____/\_____|_/\/\_|  v2
	by @Josepdal @iicc1 and @Jarriz
	
Error: DBTeam ins't working with lua5.3 and others versions, the packages must be removed, please remove them, reinstall lua5.2 and run launch.sh again.

this problem also occurs after installing luarocks (which stated dependencies over lua5.1) want to have this running but so far no luck.

Is there away for you to give me some step-by-step command to make it run? I'm setting both ubuntu or debian fresh (ubuntu 10.4 and debian 8)

**Comment by iicc1** [comment]
Can you try with some newest ubuntu version like 14 or **16**?

**Comment by ranrinc** [comment]
@iic1 sorry mistypes the version its not 10.04 but running ubuntu 16.04 as per documentation.

**Comment by ranrinc** [comment]
@iicc1 can you help me out? I mistype the ubuntu version which 16.04 and not 10.04 and the problem occurs without any way out

**Comment by Josepdal** [comment]
Join the telegram group. Link is in our channel @DBTeamEN

**Comment by iicc1** [comment]
The problem was that gcc and openssl were not installed. Added to Readme https://github.com/Josepdal/DBTeamV2/commit/d57713f4e92d42cec16236f3d755bd60e16e474f
